[package]
authors = ["Ticki <Ticki@users.noreply.github.com>"]
name = "mattermost"
version = "0.1.0"

[dependencies]
hyper = "*"

[dependencies.json_macros]
git = "https://github.com/tomjakubowski/json_macros"
